Ostore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Store.urls", namespace="store")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [
    path('', views.allProducts, name="all_products"),
    path('item/<slug:slug>/', views.productDetail, name="product_detail"),
    path('search/<slug:category_slug>/', views.categoryList, name="category_list"),
]

Store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=256, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name
    
class Product(models.Model):
    category = models.ForeignKey(Category, related_name="product", on_delete=models.CASCADE)
    createdBy = models.ForeignKey(User, on_delete=models.CASCADE, related_name="productCreator")
    title = models.CharField(max_length=256)
    author = models.CharField(max_length=256, default="admin")
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to="images/")
    slug = models.SlugField(max_length=256)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    inStock = models.BooleanField(default=True)
    isActive = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Products"
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

Store/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product

# Create your views here.
def categories(request):
    return {
        'categories': Category.objects.all()
    }

def allProducts(request):
    products = Product.objects.all()
    return render(request, 'Store/home.html', {'products':products})

def productDetail(request, slug):
    product = get_object_or_404(Product, slug=slug, inStock=True)
    return render(request, 'Store/products/detail.html', {'product':product})

def categoryList(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'Store/products/category.html', {'category':category, 'products': products})

templates/Store/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Onnee{% endblock %}</title>
        <meta name="viewport" content="width=device-width", initial-scale=1>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">OnneeStore</a>
                    <button class="naavbar-toggler" type="button" data-bs-toggle="collapse" data=bs-target="#navbar">
                    </button>
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li class="nav-item active">
                                <a class="nav-link" aria-current="page" href="/">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Link</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    Library
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>
                                        <a class="dropdown-item" href="{% url 'store:all_products' %}">All</a>
                                    </li>
                                    {% for c in categories %}
                                        <li {% if category.slug == c.slug %} class="selected" {% endif %}>
                                            <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </li>
                        </ul>
                        <form class="d-flex">
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container" id="content">
            {% block content %}
                
            {% endblock %}
        </div>
    </body>
</html>

templates/Store/home.html
{% extends "Store/base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="h1 fw-bold">Search, Read, Buy, Review</h1>
                <p class="lead text-muted">
                    Something short and leading about the collection below—its contents, the creator,
                    etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.
                </p>
                <a href="#" class="btn btn-primary my-2">Create an Account</a>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="pb-3 h5">All Products</div>
            <div class="row row-cols-1 row-cols-2 row-cols-md-5 g-3">
                {% for product in products %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
                            <div class="card-body">
                                <p class="card-text">
                                    <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                        <small class="text-muted">9min read</small>
                                </div>
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/Store/products/category.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="pb-3 h5">{{ category.name|title }}</div>
            <div class="row row-cols-1 row-cols-2 row-cols-md-5 g-3">
                {% for product in products %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
                            <div class="card-body">
                                <p class="card-text">
                                    <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                        <small class="text-muted">9min read</small>
                                </div>
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/Store/products/detail.html
{% extends "../base.html" %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.author }}</span> (Author)</p>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Hardback</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">£{{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select id="select">
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                    <option value="">4</option>
                                </select>

                            </div>
                            <div class="col-6 text-end"><button type="button" class="btn btn-secondary btn-sm">Add to
                                    basket</button></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

</div>
{% endblock %}